# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnalysisCombine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'OpenCombine', path: '../../'
  pod 'OpenCombineDispatch', path: '../../'
  pod 'OpenCombineFoundation', path: '../../'

end
