# Uncomment the next line to define a global platform for your project
platform :ios, "13.0"
inhibit_all_warnings!
use_frameworks! :linkage => :static

target 'OpenCombineExample' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  
  pod 'OpenCombine', :path => '../'
  pod 'OpenCombineDispatch', :path => '../'
  pod 'OpenCombineFoundation', :path => '../'
  pod 'CombineExt', :path => '../CombineExt/.'
  pod 'CombineCocoa', :path => '../CombineCocoa/.'

  # Pods for OpenCombineExample

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
