name: Windows 

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  windows_test:
    name: Execute tests on Windows
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["5.4.2", "5.5.1", "5.6.1", "5.7"]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-${{ matrix.swift_version }}-release
          tag: ${{ matrix.swift_version }}-RELEASE
      - name: Building and running tests in debug mode
        run: |
          swift test \
            -c debug \
            -Xswiftc -warnings-as-error
      - name: Building and running tests in release mode
        run: |
          swift test \
            -c release \
            -Xswiftc -warnings-as-errors
